### ISSUE TITLE
malicious scripts included

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-sweetcaptcha#1]
I have used this plugin these days, but the client complaint about ad popups. All in all here everything is described very detailed:

https://blog.sucuri.net/2015/06/sweetcaptcha-service-used-to-distribute-adware.html

So I think this plugin should be removed since it introduces malware in websites.

**Comment by rhukster** [comment]
Thanks for bringing this up. I'll take a look shortly.

**Comment by ntopulos** [comment]
@rhukster I was looking for a captcha plugin and found this one, but it seems that the service it relies on no longer exists. The [official site](http://www.sweetcaptcha.com/) you provide a link to, hosts some unrelated content. And when you look up "sweetcaptcha" on Google, sources mention only problems or even hijacking.

If you have some information about this service still being valid please update the links, but if not, this plugin should be removed from the getgrav website and a disclaimer put in this repository.

**Comment by hughbris** [comment]
I've just discovered this problem, luckily I have no installations of this plugin.

This was reported over two years ago and I can confirm everything reported here is still true. I think this needs to be removed from the Grav repository as it's not a good look for Grav sites.

**Comment by rhukster** [comment]
Slipped through.. removed now!
